### PR TITLE
migrate dgrijalva/jwt-go to golang-jwt/jwt-go

### PR DESCRIPTION
**Pull request by shogo82148**
github.com/dgrijalva/jwt-go is no longer maintained.

https://github.com/dgrijalva/jwt-go#readme says:

> THIS REPOSITORY IS NO LONGER MAINTANED
> The new repository can be found at: https://github.com/golang-jwt/jwt
> 
> For more information, see issue [#462](https://github.com/dgrijalva/jwt-go/issues/462).

it recommends to migrate to https://github.com/golang-jwt/jwt

### CODE REVIEW

**Comment by SVilgelm** [comment]
Fixes #54

**Comment by shogo82148** [comment]
memo: [Int.FillBytes](https://pkg.go.dev/math/big#Int.FillBytes) was added in Go 1.15.

https://github.com/bradleyfalzon/ghinstallation/pull/53/checks?check_run_id=3582316698#step:5:12

```
# github.com/golang-jwt/jwt/v4
Error: ../../../go/pkg/mod/github.com/golang-jwt/jwt/v4@v4.0.0/ecdsa.go:135:4: r.FillBytes undefined (type *big.Int has no field or method FillBytes)
Error: ../../../go/pkg/mod/github.com/golang-jwt/jwt/v4@v4.0.0/ecdsa.go:136:4: s.FillBytes undefined (type *big.Int has no field or method FillBytes)
note: module requires Go 1.15
```

**Comment by shogo82148** [comment]
@bradleyfalzon I did.

**Comment by torstenwalter** [comment]
@bradleyfalzon could you have another look?

**Comment by bradleyfalzon** [comment]
Looks good, just on mobile and will need to tag once I get near a computer

**Comment by markushinz** [comment]
@bradleyfalzon could you create new release?

**Comment by bradleyfalzon** [comment]
Apologies, released

**Pull request merged**
