### PR TITLE
Upgrade go-github to v45

### PR DESCRIPTION
**Pull request by asvoboda**

### CODE REVIEW

**Comment by asvoboda** [comment]
@bradleyfalzon / @wlynch do you mind taking a look?

**Comment by wlynch** [comment]
LGTM!

**Comment by asvoboda** [comment]
@wlynch / @bradleyfalzon do you also mind cutting a release with this change when you get an opportunity?

**Comment by wlynch** [comment]
@asvoboda https://github.com/bradleyfalzon/ghinstallation/releases/tag/v2.1.0 is now available 🎉

**Pull request merged**
