### PR TITLE
Update go-github to v50

### PR DESCRIPTION
**Pull request by asvoboda**

### CODE REVIEW

**Comment by asvoboda** [comment]
hey @wlynch do you mind taking a look when you get a chance?

**Review by wlynch — APPROVED** [review]

**Comment by wlynch** [comment]
We already have dependabot set up - it just doesn't know how to handle this library since it's a major version bump 🙁

**Comment by asvoboda** [comment]
Yeah go-github is a bit difficult with the number of major version updates. I've toyed around with https://github.com/marwan-at-work/mod, but it wouldn't handle the actual code breaks that could happen.

**Comment by dnwe** [comment]
Aside: renovatebot/renovate will attempt to do major upgrades using marwan-at-work/mod for you — yes it wouldn't help fix API changes, but it'll raise the PR and you can have it automerge if status checks (compile+test) pass

@wlynch please could you tag a new release version so we can pull in the various dependency upgrades since 2.1.0?

**Pull request merged**
