### PR TITLE
Update go-github to v39

### PR DESCRIPTION
**Pull request by asvoboda**
Updates the version of go-github to latest v39 that was recently released. https://github.com/google/go-github/releases/tag/v39.0.0

### CODE REVIEW

**Comment by shogo82148** [comment]
[go.sum](https://github.com/bradleyfalzon/ghinstallation/blob/bbcfaf2fe3242bd2307a68264656f66598aa54a1/go.sum) should be updated.
You forgot to run `go mod tidy`, didn't you?

**Comment by asvoboda** [comment]
Nice catch! Fixed :)

**Comment by asvoboda** [comment]
@wlynch do you mind taking a look when you get a chance? Thanks!

**Comment by wlynch** [comment]
LGTM. Thanks!

**Pull request merged**
